pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home')
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from pypro.base.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given e-mail must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class

    e-mail and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


'''
    OBS: o trecho abaixo é o código original da classe UserManager copiado da lib BaseUserManager
    que por alguma razão difere do código utilizado no curso e, portanto, o mesmo está adaptado
    nessa implementação, onde o parametro "username" é substituído pelo parametro "email".   


    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
'''

pypro/base/views.py
from django.http import HttpResponse

# Create your views here.
from django.shortcuts import render

def home(request):
    return render (request, 'base/home.html')

pypro/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> **Python Pro** </title>

    <meta name="description" content="Página do curso Python Pró">
    <meta name="author" content="Renzo Nuticcelli">

	<link href="{% static 'img/favicon.png' %}" rel="icon" type="image/png" >

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'base:home' %}">**Python Pró**</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
  </div>
</nav>


    <div class="container">
	<div class="row">
		<div class="col-md-12">

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="navbar-nav">
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							 <a class="nav-link" href="#">Link</a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
					<form class="form-inline">
						<input class="form-control mr-sm-2" type="text"> 
						<button class="btn btn-primary my-2 my-sm-0" type="submit">
							Search
						</button>
					</form>
					<ul class="navbar-nav ml-md-auto">
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
				</div>
			</nav>
			<div class="jumbotron">
				<h2>
					Curso de Python com Luciano Ramalho!
				</h2>
				<p>
					Confira em breve mais informações sobre o curso que será ministrado pelo autor do livro
					<a href="http://shop.oreilly.com/product/0636920032519.do" target="_blank">Python Fluente</a>
				</p>

			</div>
			<div class="card">
				<h5 class="card-header">
					Mais detalhes sobre o instrutor:
				</h5>
				<div class="card-body">
					<p class="card-text">
						<img src="{% static 'img/foto_autor.png' }" alt="foto do autor" class="img-thumbnail float_left mr-3"/>
						Luciano Ramalho é programador Python desde 1998, Fellow da Python Software Foundation;
						é sócio do Python.pro.br – uma empresa de treinamento – e cofundador do Garoa Hacker Clube,
						o primeiro hackerspace do Brasil. Tem liderado equipes de desenvolvimento de software e ministrado
						cursos sobre Python em empresas de mídia, bancos e para o governo federal.
					</p>
				</div>

			</div>
		</div>
	</div>
</div>

  <footer class="main-footer mt-5 p-4 text=light">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Entre em Contato</h3>
				<address>
					+55 12 997-411-854
					<br/>
					<a href="mailo:ramalho@python.pro.br">ramalho@python.pro.br</a>
				</address>
			</div>
		</div>
	</div>
<div class="rights pb-4">
  <div class="container">
		<div class="row">
			<div class="col">
				{% now 'Y' %} Python Pró. Todos direitos reservados.

			</div>
		</div>
	</div>

  </footer>

  </body>
</html>

pypro/base/templates/base/readme.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>LayoutIt! - Bootstrap 4</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="LayoutIt!">
</head>

<body>
	<script type="text/javascript">
		window.location.href = 'https://www.layoutit.com';
    </script>
</body>

</html>